### ISSUE TITLE
git, github package specifiers?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [heikkipora/registry-sync#21]
Does registry-sync intend to support all [valid package specifiers](https://docs.npmjs.com/cli/install#description)?

I'm getting the following error related to a github specifier:

```
registry-sync --root ./local-registry --manifest ./package-lock.json --localUrl http://localhost:9000 --binaryAbi 57,59,64 --binaryArch ia32,x64 --binaryPlatform darwin,linux,win32
(node:27415) UnhandledPromiseRejectionWarning: Error: Unknown package version async-eventemitter@github:ahultgren/async-eventemitter#fa06e39e56786ba541c180061dbf2c0a5bbf951c
    at _callee$ (/Users/michael/.local/nodeenv/registry-sync/lib/node_modules/registry-sync/src/download.js:48:19)
    at tryCatch (/Users/michael/.local/nodeenv/registry-sync/lib/node_modules/registry-sync/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/michael/.local/nodeenv/registry-sync/lib/node_modules/registry-sync/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/michael/.local/nodeenv/registry-sync/lib/node_modules/registry-sync/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/michael/.local/nodeenv/registry-sync/lib/node_modules/registry-sync/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/michael/.local/nodeenv/registry-sync/lib/node_modules/registry-sync/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
(node:27415) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27415) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The key thing being that a dependency was specified with `async-eventemitter@github:ahultgren/async-eventemitter#fa06e39e56786ba541c180061dbf2c0a5bbf951c`.

I checked that commit to make sure [it is still reachable](https://github.com/ahultgren/async-eventemitter/commit/fa06e39e56786ba541c180061dbf2c0a5bbf951c), and it is.

**Comment by michaelsbradleyjr** [comment]
Perhaps depending on the package specifier, `npm pack` could be used to download vs. axios? Or maybe `npm pack` could be used instead of axios.

It's possible to specify multiple packages for a single `npm pack` command:

```
npm pack @babel/core bluebird bluebird@3.4.7 async-eventemitter@github:ahultgren/async-eventemitter#fa06e39e56786ba541c180061dbf2c0a5bbf951c &>/dev/null
```

**Comment by michaelsbradleyjr** [comment]
I realized later that since packages specified by git/hub URLs wouldn't be in a registry anyway, what I really want to do is process a package-lock.json in the same manner as this project, but use the information to drive download of tarballs (via `npm pack`) into a standalone cache (via `npm cache add`), which can then be installed from via `npm --cache cacheDir --offline ...`.
